### ISSUE TITLE
Aim 2.0 - OPM sensor selection

### ISSUE THREAD

**Issue by contsili** [contsili/master-thesis#1]
This issue is related to commit e104426

When I ran the simulations, I vary the number of OPM sensors. That means that I need to select a subset of all the OPM sensors. As we discussed with @robertoostenveld this can be either done with Monte-Carlo simulations (which means that we need take out a different random sensor each time we ran the dipole fit iterations) or with `mesh_sphere()` function.

I decided to use the Monte-Carlo simulations. The same method is also used in Vrba, J. (2000). Multichannel SQUID biomagnetic systems. In H. Weinstock (Ed.), Applications of Superconductivity (Vol. 365, pp. 1–79). Boston; Kluwer Academic Publishers; 1999. http://www.mendeley.com/research/multichannel-squid-biomagnetic-systems/

To do that, I edited the code inside the `ni2_sensors()`. The user can now define the number of sensors in `ni2_sensors()` by using 'sensor_number' as an input argument. 

Is my idea correct? And is my code reflecting my idea correctly?

**Comment by robertoostenveld** [comment]
Random taking a subset of the existing sensors is a fine approach with me. You should only keep in mind that this will result in non-uniform subsets of channels, which _on average_ will be suboptimal for picking up the signal. No reason to change your strategy for now, just keep that in mind and document it in due time.
